phrase:
  project_id: 84a8e13ac605c1cb19dfa377a7fc97ad
  file_format: html
  # Export
  pull:
    targets:
    - file: ./en/known_issues.html
      params:
        tags: github
        file_format: html
        format_options:
          document_id: 3934e6e294252772db384fbf19398553
