phrase:
  access_token: d2d1e7c1a22e1b3fc2e644ea64e208df0ebbc80bb0f9dda2d12959bbb3cc530c
  project_id: f740d3183b3c25ffe5bc3ad222185076
  file_format: strings_json
  push:
    sources:
    - file: locales/<locale_name>/<tag>.json
      params:
       file_format: json
       update_translations: true
    #   tags: very_new239847238947294823, toast-device-hub
        # NEW
  #  - file: config/locales/frontend/fe_common/<locale_name>.yml
    #  params:
     #   file_format: yml
     #   tags: deployment_12_3_2015
      #  update_translations: true
      #  tags: tag1, very_new_tag_created
      
      
    
  pull:
    targets:
    - file: locales/sample34/<tag>.json
      params:
        file_format: strings_json
        tags: a
        locale_id: en
        locale_ids:
            - de
            - cs
        
  #  - file: locales/<locale_name>/<tag>.json
  #    params:
  #      file_format: json
  #      tags: tag2
        

#
#    - file: locales/<locale_name>/<tag>.json
#      params:
#        file_format: json
 #       tags: tag3, tag4, tag5, tag6
    # NEW
  #  - file: config/locales/frontend/fe_common/basename_language.<locale_name>.yml
    #  params:
   #     file_format: yml
     #   tag: doesntexist
