phrase:
  project_id: x
  file_format: html
  # Export
  pull:
    targets:
    - file: ./en/known_issues.html
      params:
        tags: github
        file_format: html
        format_options:
          document_id: 6b333c5a7c15517d60d3229116cb19d1
