phrase:
  project_id: 84a8e13ac605c1cb19dfa377a7fc97ad
  file_format: simple_json

  push:
    sources:
    - file: ./locales/en.json
      params:
        locale_id: 61c348f0892746681383db816026c67c
        update_translations: true
    - file: ./locales/fr.json
      params:
        locale_id: 10eb1c3b18acbd13438f61fa97d6a03c
        update_translations: true
  pull:
    targets:
    - file: ./locales/en.json
      params:
        locale_id: 61c348f0892746681383db816026c67c
        include_unverified_translations: true
    - file: ./locales/fr.json
      params:
        locale_id: 10eb1c3b18acbd13438f61fa97d6a03c
        include_unverified_translations: true
