phrase:
  project_id: 84a8e13ac605c1cb19dfa377a7fc97ad
  file_format: nested_json

  # Export
  pull:
    targets:
    - file: ./<locale_code>/auth.json
      params:
        tags: github
        file_format: nested_json
    - file: ./<locale_code>/known_issues.html
      params:
        tags: github
        file_format: html
        format_options:
          document_id: 6b333c5a7c15517d60d3229116cb19d1
